version: '3.8'

services:
  # The Flask API Backend Service
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    image: guardian-nlp-api

  # The Streamlit UI Frontend Service
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.ui
    ports:
      - "8501:8501"
    # This makes the frontend wait for the backend to be ready
    depends_on:
      - backend