# Name of your workflow
name: CI/CD Pipeline

# Trigger the workflow on a push to the main branch
on:
  push:
    branches: [ "main" ]

# Define the jobs to run
jobs:
  build-and-push:
    # Use the latest version of Ubuntu to run the job
    runs-on: ubuntu-latest

    # Define the steps in the job
    steps:
      # 1. Check out your repository's code
      - name: Check out repo
        uses: actions/checkout@v4

      # 2. Log in to Docker Hub using your secrets
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3. Build the Docker image and push it to Docker Hub
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/guardian-nlp-api:latest